# Generated by Django 3.2 on 2021-04-18 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
