version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: "./Dockerfile"
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    env_file:
      - ./.env
    ports:
    - 8000:8000
    depends_on:
      - db
    networks:
      - api_images_network



  db:
    image: library/postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postresql/data/
    env_file:
      - ./.env
    networks:
      - api_images_network


volumes:
  postgres_data:

networks:
  api_images_network:
    driver: bridge
